### ISSUE TITLE
Rotation Issues 

### ISSUE THREAD

**Issue by narobertson42** [itouch2/PhotoTweaks#25]
If trying to rotate 90 degrees to a landscape view from a portrait view it appears the limits of the window are based on the dimensions of the portrait view. Might I suggest adding either a button to rotate the image 90 degrees below the reset button or using some variant of sin((angle+M_PI_2+M_PI_4)*2)<0 to change the bounds to map height to width and width to height in those scenarios

**Comment by mxyolande** [comment]
I have the same issue. I try to add a rotate 90' button, but failed.  @itouch2
