### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by KBog** [itouch2/PhotoTweaks#3]
Hi itouch2, great module you created! :)

I edited the PhotoTweaksViewController to add a "RESET" button similar to Apple's Photos Edit feature.

At first I tried performing the reset in the PhotoTweakView class, that way I can "animate the reset", to look cool, but then I stumbled up a lot of issues because there are many moving parts (crop rect, grids, scrollview bounds, etc.)

So I ended up just adding the reset button to the PhotoTweaksVC, and drop the photoView from superview and add a new one. Which is ok, but not as cool.

Anyway, it's just a suggestion, if you have time, would be cool to have a reset button. 

Thanks!

**Comment by itouch2** [comment]
Hi, KBog. Thanks for your suggestion. I just added the "RESET" button in the PhotoTweakView class, which allows the user to reset the image similar to Apple's Photos. You can checkout the latest codes. Thanks.

**Comment by KBog** [comment]
Thanks a lot! Works great :)!
