### ISSUE TITLE
Memory Deallocations

### ISSUE THREAD

**Issue by KBog** [itouch2/PhotoTweaks#9]
Hi again!

I was running the "Analyze" in Xcode, as well as the Instruments for Memory Allocations/Leaks, and noticed that when the PhotoTweaks is used, then dismissed, the memory doesn't drop back down to where it was. Something isn't getting freed.

Running the Analyze shows in "saveBtnTapped":
Object leaked: allocated object is not referenced later in this execution path and has a retain count of +1.

I started running instruments on my app because I noticed that it's getting a lot of low memory warnings from the iOS SDK.

**Comment by RyanBertrand** [comment]
Hi,
The CGImageRef needs to be released when it is done being used.  Notice the **new** prefix in **newTransformedImage:sourceImage:sourceSize:sourceOrientation:outputWidth:cropSize:imageViewSize:** method.  This indicates the return value is retained which now becomes your memory to handle.

``` objective-c
- (void)saveBtnTapped
{
    ...
    CGImageRelease(imageRef);
    [self.navigationController popViewControllerAnimated:YES];
}
```

**Comment by itouch2** [comment]
Thanks for you two. I just fixed the memory issue.

@RyanBertrand  FYI, It should use `image.CGImage` to be saved to photos, or the imageRef may got deallocated when save to photo. Thanks.

``` objective-c
UIImage *image = [UIImage imageWithCGImage:imageRef];
if ([self.delegate respondsToSelector:@selector(finishWithCroppedImage:)]) {
    [self.delegate finishWithCroppedImage:image];
}

if (self.autoSaveToLibray) {
    ALAssetsLibrary *library = [[ALAssetsLibrary alloc] init];
    [library writeImageToSavedPhotosAlbum:image.CGImage metadata:nil completionBlock:^(NSURL *assetURL, NSError *error) {
        if (!error) {
        }
    }];
} else {
}

CGImageRelease(imageRef);
[self.navigationController popViewControllerAnimated:YES];

```

**Comment by RyanBertrand** [comment]
Awesome - Thanks!

**Comment by KBog** [comment]
Great! Thanks!
